---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ansible_distribution_major_version }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Install epel
  yum: name={{ epel_url }} state=present update_cache=yes
  when: ansible_os_family == "RedHat"

- name: Ensure required packages are installed
  action: "{{ package_info.pkg_mgr }}"
  args: package_info.args
  with_items: package_info.pkgs
  when: package_info.pkgs|length > 0

- include: spark_stack.yml 
  when: spark_stack and ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Update all packages
  action: "{{ update_info.pkg_mgr }}"
  args: update_info.args

- name: Make sure the NTP service is stopped
  service: name={{ ntp_service }} state=stopped

- name: Force NTP sync
  command: "{{ ntp_sync }}"

- name: Start the NTP service
  service: name={{ ntp_service }} state=started enabled=yes

- name: Disable MySQL skip-name-resolve if present
  lineinfile: dest=/etc/my.cnf
              regexp="^skip[-_]name[-_]resolve"
              state=absent

- name: Set nofile limits
  lineinfile: dest=/etc/security/limits.conf
              insertbefore="^# End of file"
              state=present
              line="{{ item }}"
  with_items:
    - "* soft nofile 32768"
    - "* hard nofile 32768"

- name: Set nproc limits
  lineinfile: dest=/etc/security/limits.d/90-nproc.conf
              insertafter=EOF
              state=present
              create=yes
              line="{{ item }}"
              mode=0644
  with_items:
    - "* soft nproc 32768"
    - "* hard nproc 32768"

- name: Load bridge kernel module to prevent sysctl errors
  modprobe: name=bridge state=present

- name: Set swappiness to 1
  sysctl: name=vm.swappiness value=1 state=present

- name: Set the tuned profile
  copy: src=tuned.conf
        dest=/etc/tuned/hadoop/
        mode=0755
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Activate the tuned profile
  shell: tuned-adm profile hadoop
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Get number of kernels in grub.conf
  shell: grep -E "^[[:blank:]]*kernel" /boot/grub/grub.conf | grep -v transparent_hugepage
  register: grep_result
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
  ignore_errors: true

- name: Disable Transparent Huge Pages in Grub 1
  lineinfile: dest=/boot/grub/grub.conf
              backrefs=True
              state=present
              regexp='(^\s*kernel(\s+(?!transparent_hugepage=never)[\w=/\-\.\,]+)*)\s*$'
              line='\1 transparent_hugepage=never'
  register: result
  with_items: grep_result.stdout_lines
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Disable Transparent Huge Pages in Grub 2
  lineinfile: dest=/etc/default/grub
              state=present
              line='GRUB_CMDLINE_LINUX=$GRUB_CMDLINE_LINUX" transparent_hugepage=never"'
  when: "{{ ansible_distribution_major_version|int }} > 6"

- name: Run update-grub in Grub 2
  shell: "{{ update_grub }}"
  when: "{{ ansible_distribution_major_version|int }} > 6"

- name: Disable Transparent Huge Pages until reboot
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
  ignore_errors: true

- name: Reconfigure resolv.conf domain
  lineinfile: dest={{ resolv_conf }}
              create=yes
              regexp='^domain\s+(?! {{ ansible_domain }} ).*$'
              line='domain {{ ansible_domain }}'
  when: ansible_domain != ""

- name: Reconfigure resolv.conf search
  lineinfile: dest={{ resolv_conf }}
              create=yes
              regexp='^search\s+(?! {{ ansible_domain }} ).*$'
              line='search {{ ansible_domain }}'
  when: ansible_domain != ""

- name: Run resolvconf
  shell: resolvconf -u
  when: ansible_os_family == "Debian"

- name: Configure bonding
  include: bonding.yml
  when: bond_interfaces is defined

- name: Set hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=0644

- include: unbound-dns.yml 
  when: use_dns

- include: firewall.yml
  when: cloud_nodes_count is defined and cloud_nodes_count > 0

- include: partitioning.yml
