packages:
  - python-simplejson
  - python-httplib2
  - man
  - man-pages
  - vim-enhanced
  - sysstat
  - lsof
  - jwhois
  - telnet
  - nc
  - libselinux-python
  - ntpdate
  - chrony
  - parted
  - mc
  - perl
  - openssh-clients
  - util-linux-ng
  - iotop
  - links
  - unzip
  - curl
  - wget

update_info:
  pkg_mgr: yum
  args:
    pkg: "*"
    state: latest
    update_cache: yes

update_grub: 'grub2-mkconfig -o "$(readlink -n /etc/grub2.cfg)"'

ntp_service: chronyd
ntp_sync: "systemctl restart ntpdate"

epel_url: "https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm"

resolv_conf: "/etc/resolv.conf"

networking_path: "/etc/sysconfig/network-scripts"
networking_eth: "redhat-ifcfg-eth.j2"
networking_bond: "redhat-ifcfg-bond.j2"
