ambari_repo: "http://public-repo-1.hortonworks.com/ambari/centos{{ ansible_distribution_major_version }}/2.x/updates/{{ ambari_version }}/ambari.repo"
ambari_repo_file: "/etc/yum.repos.d/ambari.repo"
