---
- include: create_groups.yml
  tags:
    - always

- name: "gather facts"
  hosts: hadoop-cluster
  gather_facts: true

- name: "generate site facts"
  hosts: localhost 
  any_errors_fatal: true
  become: no
  vars: 
    dnmemory: "{{ hostvars[groups['slave-nodes'][0]]['ansible_memtotal_mb'] / 1024 }}"
    mnmemory: "{{ hostvars[groups['master-nodes'][0]]['ansible_memtotal_mb'] / 1024 }}"
    cores: "{{ hostvars[groups['slave-nodes'][0]]['ansible_processor_count'] }}"
  tasks:
    - name: "run yarn utlils"
      action:
        module: sitefacts.py
          dnmemory="{{ dnmemory }}"
          mnmemory="{{ mnmemory }}"
          cores="{{ cores }}"

- name: "debug"
  hosts: localhost
  tasks:
   -  debug: 
        msg:
         - "ams_env['metrics_collector_heapsize'] : {{ hostvars['localhost']['ams_env']['metrics_collector_heapsize'] }}"
         - "ams_hbase_env['hbase_master_heapsize'] : {{ hostvars['localhost']['ams_hbase_env']['hbase_master_heapsize'] }}"
         - "ams_hbase_env['hbase_master_xmn_size'] : {{ hostvars['localhost']['ams_hbase_env']['hbase_master_xmn_size'] }}"
         - "ams_hbase_env['hbase_regionserver_heapsize'] : {{ hostvars['localhost']['ams_hbase_env']['hbase_regionserver_heapsize'] }}"
         - "ams_hbase_env['regionserver_xmn_size'] : {{ hostvars['localhost']['ams_hbase_env']['regionserver_xmn_size'] }}"
         - "hadoop_env['dtnode_heapsize'] : {{ hostvars['localhost']['hadoop_env']['dtnode_heapsize'] }}"
         - "hadoop_env['namenode_heapsize'] : {{ hostvars['localhost']['hadoop_env']['namenode_heapsize'] }}"
         - "hadoop_env['namenode_opt_maxnewsize'] : {{ hostvars['localhost']['hadoop_env']['namenode_opt_maxnewsize']}}"
         - "hadoop_env['namenode_opt_newsize'] : {{ hostvars['localhost']['hadoop_env']['namenode_opt_newsize'] }}"
         - "hbase_env['hbase_master_heapsize'] : {{ hostvars['localhost']['hbase_env']['hbase_master_heapsize'] }}"
         - "hbase_env['hbase_regionserver_heapsize'] : {{ hostvars['localhost']['hbase_env']['hbase_regionserver_heapsize'] }}"
         - "hbase_env['hbase_regionserver_xmn_max'] : {{ hostvars['localhost']['hbase_env']['hbase_regionserver_xmn_max'] }}"
         - "hbase_site['hbase_master_wait_on_regionservers_timeout'] : {{ hostvars['localhost']['hbase_site']['hbase_master_wait_on_regionservers_timeout'] }}"
         - "hbase_site['hbase_master_namespace_init_timeout'] : {{ hostvars['localhost']['hbase_site']['hbase_master_namespace_init_timeout'] }}"
         - "hbase_site['hbase_regionserver_executor_openregion_threads'] : {{ hostvars['localhost']['hbase_site']['hbase_regionserver_executor_openregion_threads'] }}"
         - "core_site['fs_trash_interval'] : {{ hostvars['localhost']['core_site']['fs_trash_interval'] }}"
         - "hdfs_site['dfs_datanode_balance_bandwidthPerSec'] : {{ hostvars['localhost']['hdfs_site']['dfs_datanode_balance_bandwidthPerSec'] }}"
         - "hdfs_site['dfs_datanode_max_transfer_threads'] : {{ hostvars['localhost']['hdfs_site']['dfs_datanode_max_transfer_threads'] }}"
         - "hdfs_site['dfs_replication'] : {{ hostvars['localhost']['hdfs_site']['dfs_replication'] }}"
         - "hive_env['hive_client_heapsize'] : {{ hostvars['localhost']['hive_env']['hive_client_heapsize'] }}"
         - "hive_env['hive_heapsize'] : {{ hostvars['localhost']['hive_env']['hive_heapsize'] }}"
         - "hive_env['hive_metastore_heapsize'] : {{ hostvars['localhost']['hive_env']['hive_metastore_heapsize'] }}"
         - "hive_site['hive_tez_container_size'] : {{ hostvars['localhost']['hive_site']['hive_tez_container_size'] }}"
         - "hive_site['fs_file_impl_disable_cache'] : {{ hostvars['localhost']['hive_site']['fs_file_impl_disable_cache'] }}"
         - "hive_site['fs_hdfs_impl_disable_cache'] : {{ hostvars['localhost']['hive_site']['fs_hdfs_impl_disable_cache'] }}"
         - "hive_site['hive_plan_serialization_format'] : {{ hostvars['localhost']['hive_site']['hive_plan_serialization_format'] }}"
         - "hive_site['hive_execution_engine'] : {{ hostvars['localhost']['hive_site']['hive_execution_engine'] }}"
         - "hive_site['hive_exec_compress_intermediate'] : {{ hostvars['localhost']['hive_site']['hive_exec_compress_intermediate'] }}"
         - "hive_site['hive_exec_compress_output'] : {{ hostvars['localhost']['hive_site']['hive_exec_compress_output'] }}"
         - "hive_site['hive_merge_mapfiles'] : {{ hostvars['localhost']['hive_site']['hive_merge_mapfiles'] }}"
         - "hive_site['hive_default_fileformat_managed'] : {{ hostvars['localhost']['hive_site']['hive_default_fileformat_managed'] }}"
         - "hive_site['hive_compute_query_using_stats'] : {{ hostvars['localhost']['hive_site']['hive_compute_query_using_stats'] }}"
         - "hive_site['hive_cbo_enable'] : {{ hostvars['localhost']['hive_site']['hive_cbo_enable'] }}"
         - "hive_site['hive_stats_fetch_column_stats'] : {{ hostvars['localhost']['hive_site']['hive_stats_fetch_column_stats'] }}"
         - "hive_site['hive_stats_fetch_partition_stats'] : {{ hostvars['localhost']['hive_site']['hive_stats_fetch_partition_stats'] }}"
         - "hive_site['hive_vectorized_execution_reduce_enabled'] : {{ hostvars['localhost']['hive_site']['hive_vectorized_execution_reduce_enabled'] }}"
         - "hive_site['hive_server2_tez_initialize_default_sessions'] : {{ hostvars['localhost']['hive_site']['hive_server2_tez_initialize_default_sessions'] }}"
         - "mapred_site['mapreduce_map_java_opts'] : {{ hostvars['localhost']['mapred_site']['mapreduce_map_java_opts'] }}"
         - "mapred_site['mapreduce_map_memory_mb'] : {{ hostvars['localhost']['mapred_site']['mapreduce_map_memory_mb'] }}"
         - "mapred_site['mapreduce_reduce_java_opts'] : {{ hostvars['localhost']['mapred_site']['mapreduce_reduce_java_opts'] }}"
         - "mapred_site['mapreduce_reduce_memory_mb'] : {{ hostvars['localhost']['mapred_site']['mapreduce_reduce_memory_mb'] }}"
         - "mapred_site['mapreduce_task_io_sort_mb'] : {{ hostvars['localhost']['mapred_site']['mapreduce_task_io_sort_mb'] }}"
         - "mapred_site['yarn_app_mapreduce_am_command_opts'] : {{ hostvars['localhost']['mapred_site']['yarn_app_mapreduce_am_command_opts'] }}"
         - "mapred_site['yarn_app_mapreduce_am_resource_mb'] : {{ hostvars['localhost']['mapred_site']['yarn_app_mapreduce_am_resource_mb'] }}"
         - "mapred_site['mapreduce_output_fileoutputformat_compress'] : {{ hostvars['localhost']['mapred_site']['mapreduce_output_fileoutputformat_compress'] }}"
         - "mapred_site['mapreduce_map_output_compress'] : {{ hostvars['localhost']['mapred_site']['mapreduce_map_output_compress'] }}"
         - "mapred_site['mapreduce_job_reduce_slowstart_completedmaps'] : {{ hostvars['localhost']['mapred_site']['mapreduce_job_reduce_slowstart_completedmaps'] }}"
         - "spark_defaults['spark_driver_memory'] : {{ hostvars['localhost']['spark_defaults']['spark_driver_memory'] }}"
         - "spark_defaults['spark_yarn_am_memory'] : {{ hostvars['localhost']['spark_defaults']['spark_yarn_am_memory'] }}"
         - "spark_defaults['spark_yarn_am_memoryOverhead'] : {{ hostvars['localhost']['spark_defaults']['spark_yarn_am_memoryOverhead'] }}"
         - "spark_defaults['spark_yarn_driver_memoryOverhead'] : {{ hostvars['localhost']['spark_defaults']['spark_yarn_driver_memoryOverhead'] }}"
         - "spark_defaults['spark_yarn_executor_memoryOverhead'] : {{ hostvars['localhost']['spark_defaults']['spark_yarn_executor_memoryOverhead'] }}"
         - "spark_defaults['sparn_executor_memory'] : {{ hostvars['localhost']['spark_defaults']['spark_yarn_executor_memory'] }}"
         - "tez_site['tez_am_resource_memory_mb'] : {{ hostvars['localhost']['tez_site']['tez_am_resource_memory_mb'] }}"
         - "tez_site['tez_task_resource_memory_mb'] : {{ hostvars['localhost']['tez_site']['tez_task_resource_memory_mb'] }}"
         - "tez_site['tez_am_launch_cmd-opts'] : {{ hostvars['localhost']['tez_site']['tez_am_launch_cmd-opts'] }}"
         - "yarn_site['yarn_nodemanager_resource_memory_mb'] : {{ hostvars['localhost']['yarn_site']['yarn_nodemanager_resource_memory_mb'] }}"
         - "yarn_site['yarn_scheduler_maximum_allocation_mb'] : {{ hostvars['localhost']['yarn_site']['yarn_scheduler_maximum_allocation_mb'] }}"
         - "yarn_site['yarn_timeline-service_store-class'] : {{ hostvars['localhost']['yarn_site']['yarn_timeline-service_store-class'] }}"
         - "yarn_site['yarn_timeline-service_generic-application-history_save-non-am-container-meta-info'] : {{ hostvars['localhost']['yarn_site']['yarn_timeline-service_generic-application-history_save-non-am-container-meta-info'] }}"
         - "zeppelin_env['zeppelin_executor_memory'] : {{ hostvars['localhost']['zeppelin_env']['zeppelin_executor_memory'] }}"
         - "zeppelin_env['zeppelin_executor_instances'] : {{ hostvars['localhost']['zeppelin_env']['zeppelin_executor_instances'] }}"
      when: debug
