---
- name: Ensure required packages are installed (yum)
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - mysql-connector-java
    - ambari-server
  notify: Reload systemd
  when: ansible_os_family == "RedHat"

- name: Ensure required packages are installed (apt)
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - ambari-server
  when: ansible_os_family == "Debian"

- include: unbound-dns.yml
  when: use_dns

- meta: flush_handlers

- include: arcadia.yml
  when: arcadia and ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Run Ambari Server setup
  shell: /usr/sbin/ambari-server setup -s --jdbc-db=mysql --jdbc-driver=/usr/share/java/mysql-connector-java.jar

- name: Make sure ambari-server is running
  command: service ambari-server restart

- name: Waiting for ambari-server to start listening on port 8080
  wait_for: host={{ ansible_nodename }} port=8080

- name: Change Ambari admin user password
  uri: url=http://{{ ansible_nodename }}:8080/api/v1/users/admin
       method=PUT
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       body=' {"Users":{ "password":"{{ admin_password }}", "old_password":"admin"}}'
       body_format=raw
       status_code=200,201,202,403
  when: admin_password != 'admin'

- name: Waiting for ambari-agents to register
  uri: url=http://{{ ansible_nodename }}:8080/api/v1/hosts/{{ hostvars[item]['ansible_nodename'] | lower }}
       method=GET
       force_basic_auth=yes
       user=admin
       password={{ admin_password }}
       HEADER_X-Requested-By="ambari"
       status_code=200,201,202,404
  with_items: "{{ groups['hadoop-cluster'] }}"
  register: result
  until: "result.status != 404"
  retries: 200
  delay: 5
